### ISSUE TITLE
it not work show me this error in console

### ISSUE THREAD

**Issue by malmahdi-openalt** [paurosello/linktitle#1]
linktitle.js:
 168 Uncaught (in promise) TypeError: this.$input.autocomplete is not a function

**Comment by paurosello** [comment]
hello @malmahdi-openalt this was released for frappe v8 and was just a demo to see if the maintanters were interested in this...

I don't have time to update it right now and unfortunately it is not a good solution as there are many other places that would need a fix for this.

I recommend using a readonly field to show the value that you want (it's the best solution I have found)
